In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
data = pd.read_csv("Data.csv")
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [8]:
data.shape

(9568, 5)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [10]:
data.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [11]:
# PE is to be predicted
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [15]:
lr.fit(X_train, y_train)

LinearRegression()

In [19]:
y_train_pred = lr.predict(X_train)
y_train_pred

array([448.43580137, 475.09199415, 478.15156236, ..., 439.08535981,
       469.5776115 , 469.7003965 ])

In [20]:
y_train

array([443.31, 490.96, 483.94, ..., 435.06, 471.13, 472.43])

In [23]:
y_pred_test = lr.predict(X_test)
y_pred_test

array([455.68020791, 438.73212215, 434.16444   , ..., 482.16817365,
       435.41524413, 458.76150613])

In [31]:
np.set_printoptions(precision=2)
np.concatenate((y_pred_test.reshape(len(y_pred_test), 1), y_test.reshape(len(y_test), 1)), 1)

array([[455.68, 455.27],
       [438.73, 436.31],
       [434.16, 440.68],
       ...,
       [482.17, 479.53],
       [435.42, 435.76],
       [458.76, 457.1 ]])

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_test)

0.9301046431962188