In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Data.csv")
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
# PE is to be predicted
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [12]:
# It is important to reshape in SVR
y = y.reshape(-1,1)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Feature scaling

In [14]:
X_train

array([[  21.92,   49.02, 1009.29,   88.56],
       [  11.09,   40.43, 1025.47,   74.97],
       [   8.49,   39.61, 1021.05,   87.74],
       ...,
       [  27.79,   69.23, 1012.86,   45.71],
       [  12.26,   41.5 , 1014.87,   89.41],
       [  11.75,   40.55, 1018.09,   97.7 ]])

In [15]:
from sklearn.preprocessing import StandardScaler
sr_X = StandardScaler()
X_train = sr_X.fit_transform(X_train)
X_train

array([[ 0.30884304, -0.41258437, -0.66692982,  1.04050751],
       [-1.14790306, -1.08849369,  2.05467132,  0.11116543],
       [-1.49762974, -1.15301588,  1.31119314,  0.98443242],
       ...,
       [ 1.09841826,  1.17765165, -0.06642821, -1.88975799],
       [-0.99052606, -1.00430009,  0.27166934,  1.09863413],
       [-1.05912629, -1.07905142,  0.81329824,  1.66553964]])

In [16]:
y_train

array([[443.31],
       [490.96],
       [483.94],
       ...,
       [435.06],
       [471.13],
       [472.43]])

In [17]:
sr_y = StandardScaler()
y_train = sr_y.fit_transform(y_train)
y_train

array([[-0.65133557],
       [ 2.1394232 ],
       [ 1.72827679],
       ...,
       [-1.13452046],
       [ 0.97802244],
       [ 1.05416066]])

In [19]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf')
svr.fit(X_train, y_train)

/Users/laasya/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [24]:
y_pred_train = sr_y.inverse_transform(svr.predict(X_train).reshape(-1,1))
y_pred_train

array([[446.32156348],
       [475.42267743],
       [481.30503358],
       ...,
       [438.10302456],
       [471.95436035],
       [469.0492421 ]])

In [23]:
y_pred_test = sr_y.inverse_transform(svr.predict(sr_X.transform(X_test)).reshape(-1,1))
y_pred_test

array([[456.77153288],
       [437.11173548],
       [434.62000556],
       ...,
       [483.16235984],
       [435.35109294],
       [458.55458652]])

In [25]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_test)

0.9468436098144656